### ISSUE TITLE
Avoiding "already initialized constant errors" with net/protocol

### ISSUE THREAD

**Issue by stanhu** [ruby/net-imap#16]
If I have a gem that depends on `net/imap` v0.2.1, I see that it conflicts with the Ruby interpreter's version:

```shell
$ bundle exec rspec spec
/home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/travis/.rvm/gems/ruby-2.6.6/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/travis/.rvm/gems/ruby-2.6.6/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/travis/.rvm/gems/ruby-2.6.6/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
```

Is there a way this updated version of the gem can be used as a separate dependency without generating these warnings? https://stackoverflow.com/a/9117903/1992201 has some suggestions, but these still seem like hacks. Does it make sense to remove `net/protocol` as a hard dependency? MRI appears to have an exact copy of `protocol.rb`.

**Comment by shugo** [comment]
net/protocol and net/imap have been default gems since Ruby 3.0, so it may introduce problems to  remove net-protocol from dependencies.
On Ruby 2.6, net/imap itself is not a (default) gem, so it may be hard to use the net-imap gem without hacks.

@hsbt What do you think?

**Comment by deivid-rodriguez** [comment]
@stanhu I'm interested in this is issue. Can you share steps to reproduce the warnings?

**Comment by stanhu** [comment]
@deivid-rodriguez The easiest way I've been able to reproduce it:

```shell
git clone git@github.com:tpitale/mail_room.git
cd mail_room
echo 2.7.2 > .ruby_version # Choose your version
bundle exec rspec spec/lib/mailbox_spec.rb
```

**Comment by deivid-rodriguez** [comment]
Thanks, I'll have a look!

**Comment by deivid-rodriguez** [comment]
The proper fix here in my opinion would be that the [faraday-net_http gem](https://github.com/lostisland/faraday-net_http) would declare the `net-http` gem as a dependency.

This is the explanation of what's happening:

* When the `faraday-net_http` gem is required, it then requires `net/http`.
* Then the stdlib version of `net/http` is loaded, since bundler doesn't know `net-http` is a gem dependency, so it doesn't add the gemified version to to the `$LOAD_PATH`.
* Then the stdlib version of `net/http` requires `net/protocol` relatively, since that's what it used to happen before these gems were gemified. See https://github.com/ruby/net-http/commit/6da598e928f0cc817b1d17209dfaf7fed4c9dff7. So the stdlib version of `net/protocol` is loaded.
* Then when `net-imap` is required, it also uses `net-protocol` but this time the gemified version of `net-protocol` is used, because `net-imap` properly declares it as a dependency, so `bundler` knows about it and has put it in the `$LOAD_PATH`. This is what causes the double load of `net/protocol`.

If `faraday-net_http` explicitly declares `net-http` as a dependency, then the gemified version of all gems involved will be consistently loaded and there will be no redefinition warnings.

I suggest that you proposed this update to `faraday-net_http` and in the mean time, you can workaround this issue by adding `gem "net-http"` to your `Gemfile`.

**Comment by stanhu** [comment]
@deivid-rodriguez Thanks for that tip! That seems to work well. I've submitted https://github.com/lostisland/faraday-net_http/pull/5 and https://github.com/tpitale/mail_room/pull/123.

**Comment by stanhu** [comment]
It seem the one issue is that net-http requires Ruby 2.6, so older Rubies won't work with this `add_dependency`.

**Comment by hsbt** [comment]
It's not related dependencies of gemspec.

**Comment by deivid-rodriguez** [comment]
> One issue is that net-http requires Ruby 2.6, so older Rubies won't work with this add_dependency.

Oh, I see, that's unfortunate. I guess you need to workaround this via `Gemfile` until other dependencies also drop Ruby 2.5 support :(. For what it's worth, ruby 2.5 was dropped at https://github.com/ruby/net-http/commit/e6ab6d72e4b9f1e17bbaa6f4c7a5165ded0aaada. My guess is that the only reason was that CI didn't pass.

**Comment by deivid-rodriguez** [comment]
Cointidentially I run into a similar instance of this issue myself today. To make things easier for gem authors and motivate them to add the dependency, I propose to release at least one gemified version of `net-http` that supports ruby 2.5. I proposed that at https://github.com/ruby/net-http/pull/19.

**Comment by mrbrdo** [comment]
To get around the issue, I had to add more gems, and after trying to deploy I found I had to add the uri gem as well:
```ruby
gem "net-http"
gem "net-smtp"
gem "net-imap"
gem "uri", "0.10.0"
```
However if I use any `gem 'name', path: '/path'` in the Gemfile, that causes a large amonut of warnings upon app boot.

**Comment by FaxriddinMaxmadiyorov** [comment]
> The proper fix here in my opinion would be that the [faraday-net_http gem](https://github.com/lostisland/faraday-net_http) would declare the `net-http` gem as a dependency.
> 
> This is the explanation of what's happening:
> 
> * When the `faraday-net_http` gem is required, it then requires `net/http`.
> * Then the stdlib version of `net/http` is loaded, since bundler doesn't know `net-http` is a gem dependency, so it doesn't add the gemified version to to the `$LOAD_PATH`.
> * Then the stdlib version of `net/http` requires `net/protocol` relatively, since that's what it used to happen before these gems were gemified. See [ruby/net-http@6da598e](https://github.com/ruby/net-http/commit/6da598e928f0cc817b1d17209dfaf7fed4c9dff7). So the stdlib version of `net/protocol` is loaded.
> * Then when `net-imap` is required, it also uses `net-protocol` but this time the gemified version of `net-protocol` is used, because `net-imap` properly declares it as a dependency, so `bundler` knows about it and has put it in the `$LOAD_PATH`. This is what causes the double load of `net/protocol`.
> 
> If `faraday-net_http` explicitly declares `net-http` as a dependency, then the gemified version of all gems involved will be consistently loaded and there will be no redefinition warnings.
> 
> I suggest that you proposed this update to `faraday-net_http` and in the mean time, you can workaround this issue by adding `gem "net-http"` to your `Gemfile`.

thank you, I resolved the problem

**Comment by iMacTia** [comment]
Hi @deivid-rodriguez, I'd like to chime in on the discussion since I've been asked multiple times to add `net-http` as a dependency to`faraday-net_http` as a result of your comment and I'm not completely sure yet if that's the correct thing to do.

I explained my understanding of the issue in [this comment](https://github.com/lostisland/faraday-net_http/pull/5#issuecomment-854762189) and why I believe it is a mistake to add these gems explicitly in gemspec. 

If faraday were to add `net-http` as a dependency, it would force every project using it to switch to the gemified version of the libray. This would be OK on Ruby 3.0, but it might be a disaster for previous rubies, where the stdlib version is still present.

For example, I'd expect [issues like this](https://github.com/getsentry/sentry-ruby/issues/1837#issuecomment-1172869984) to pop up if I did that.

I'm not sure why some gems have started adding explicit dependencies to these gems, but it seems like letting Ruby figuring it out by itself (when to use the stdlib or the standard gem) is the best way to avoid this mix and match and support both Rubies older and newer than 3.0.

I understand some people are affected by this issue because they use a gem that has added one of these dependencies to their gemspec, and I can see why it's annoying to now having to add more dependencies themselves.
But as I see it, if I were to add the same dependency to faraday this could actually increase the conflicts rather than improving the situation.

It would be great to discuss this and agree to a solution that could benefit everyone 🙏

**Comment by deivid-rodriguez** [comment]
Sorry I don't have a lot of time to look into this right now, but I can say something similar to this has been discussed in the upstream Ruby tracker, and there's no agreement. For example, https://bugs.ruby-lang.org/issues/16951. Note that I did propose https://github.com/ruby/net-http/pull/19 after that message you mention to avoid this problem, but it didn't happen.

Not sure about your specific situation and the range of rubies where issues would pop up vs the range of rubies that would benefit from it. If this would only cause problems on rubies that have reached EOL, and those problems are only warnings, then I do think it's worth prioritizing users of supported rubies. But you know best what makes more sense for your libraries, and of course you're happy to chime in in the core tracker and propose any solutions. As I said, I don't have a lot of time right now, sorry :(

**Comment by deivid-rodriguez** [comment]
No problem, sorry I can't help more right now, and I appreciate your conciousness and will to get to the bottom of things.

**Comment by voxik** [comment]
> it would force every project using it to switch to the gemified version of the libray.

This is very vague claim and might or might not be true. It very much depends on the context.

>  it might be a disaster for previous rubies, where the stdlib version is still present.

This is overstatement. Generally, there is nothing wrong in using gemified version of library in old Ruby. The `net-http` gem supports Ruby 2.6+, so unless you talk about way older versions of Ruby, then it should be just fine.

**Comment by deivid-rodriguez** [comment]
Right, I'm still unclear about the issue with newer rubies. There's many moving parts so there could be some issue, I just don't know what it is right now.

As I have pointed out in other places, adding explicit dependencies helps Bundler and RubyGems provide consistent results. And also helps users because the exact gem version is recorded in the lockfile just like any other dependency, so you get consistent results when using the dependency even if you switch rubies.

**Comment by gepinedo** [comment]
> gem "net-http"

Thanks, @deivid-rodriguez, it works perfectly!

**Comment by gepinedo** [comment]
> > The proper fix here in my opinion would be that the [faraday-net_http gem](https://github.com/lostisland/faraday-net_http) would declare the `net-http` gem as a dependency.
> > This is the explanation of what's happening:
> > 
> > * When the `faraday-net_http` gem is required, it then requires `net/http`.
> > * Then the stdlib version of `net/http` is loaded, since bundler doesn't know `net-http` is a gem dependency, so it doesn't add the gemified version to to the `$LOAD_PATH`.
> > * Then the stdlib version of `net/http` requires `net/protocol` relatively, since that's what it used to happen before these gems were gemified. See [ruby/net-http@6da598e](https://github.com/ruby/net-http/commit/6da598e928f0cc817b1d17209dfaf7fed4c9dff7). So the stdlib version of `net/protocol` is loaded.
> > * Then when `net-imap` is required, it also uses `net-protocol` but this time the gemified version of `net-protocol` is used, because `net-imap` properly declares it as a dependency, so `bundler` knows about it and has put it in the `$LOAD_PATH`. This is what causes the double load of `net/protocol`.
> > 
> > If `faraday-net_http` explicitly declares `net-http` as a dependency, then the gemified version of all gems involved will be consistently loaded and there will be no redefinition warnings.
> > I suggest that you proposed this update to `faraday-net_http` and in the mean time, you can workaround this issue by adding `gem "net-http"` to your `Gemfile`.
> 
> thank you, I resolved the problem

Thanks, @deivid-rodriguez, it works perfectly!

**Comment by evolve2k** [comment]
_Cross posting a refinement our similar comment on  https://github.com/mikel/mail/issues/1523_

I've been pairing on this with a few folk at [RubyRetreat AU 2024](https://retreat.ruby.org.au/) in an attempt to get to the bottom of this. Thanks crew! @KJTsanaktsidis @moxvallix @layerssss

The impact of this issue extends beyond the mail gem and is likley affecting most apps attempting to upgrade from Rails 5.1 to Rails 6.x on their journey through a rails upgrade path. Rails relies on this mail gem which in turn is relying on net-http, which is where the conflicts lie.

net/http is only gemified from ruby 3.0 BUT all versions of the net-http gem (v0.1.0 up to latest 0.4.1) list an incorrect minimum support ruby as being >= 2.6.0, but it should be listed as >=3.0

A few compounding issues:

- net-http gem on rubygems lists incorrect minimum ruby
- ruby standard library doesnt set clear version dependancies on net-http amplifying this issue.
- mail brings in net-http, net-imap, net-smtp they all have the same problem, but this adds further confusion

WORKAROUND PROCESS:
Review Gemfile.lock and look for dependancies on net-imap, net-http, net-smpt in my case the mail gem.
Pin each of the dependant gems to a [version circa ruby 2.6](https://www.ruby-lang.org/en/downloads/releases/), eg around 2018.

**Comment by abdelbk** [comment]
What about ruby versions prior to 2.6 (2.5 in our case) ? The workaround to include the `net-http` gem does not work because it requires at least ruby 2.6.

We are having the same warnings upon upgrading to rails 6.1

Is it ok to keep those warnings until we upgrade to ruby 2.6 and include the `net-http` gem ?
